name: shihwallet
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  wallet_connect:
    path: ./wallet-connect-dart/
  flutter_trust_wallet_core:
    git:
      url: https://github.com/weishirongzhen/flutter_trust_wallet_core_lib_include.git
      ref: 8e371e1aadcf06f2d1ce44fb3036a36395d1f095
  cupertino_icons: ^1.0.2
  syncfusion_flutter_charts: ^19.2.55+1
  barcode: ^2.1.0
  provider: ^5.0.0
  google_fonts: ^2.1.0
  convert: ^3.0.1
  http: ^0.13.3
  clipboard: ^0.1.3
  toast: ^0.1.5
  flutter_secure_storage: ^4.2.1
  flutter_launcher_icons: ^0.9.2
  web_socket_channel: ^2.1.0
  eth_sig_util: ^0.0.3
  flutter_inappwebview: ^5.3.2
  barcode_widget: ^2.0.1
  share: ^2.0.4
  url_launcher: ^6.0.10
  web3dart: ^2.3.2
  awesome_notifications: ^0.6.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  persistent_bottom_nav_bar: ^4.0.2
  pin_code_fields: ^7.3.0


flutter:

  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/onboarding/
    - assets/bottomBar/
    - assets/mainScreen/
    - assets/setting/
    - assets/icons/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/ic_launcher/1024.png"